const mottos = [
    "Just do it", "Stay hungry, stay foolish", "Believe in yourself", "Never give up", "Carpe Diem",
    "Dream big", "Work hard, stay humble", "Be kind always", "Stay positive", "Keep moving forward",
    "Focus on the good", "Make it happen", "Be your own hero", "Choose joy", "Live in the moment",
    "Follow your heart", "Stay strong", "Be the change", "Do what you love", "Love what you do",
    "Don't stop until you're proud", "Everything happens for a reason", "Good things take time", "Progress over perfection", "You are enough",
    "Start where you are", "Use what you have", "Do what you can", "Breathe in, breathe out", "Happiness is a choice",
    "Keep it simple", "Learn something new every day", "Success is a journey", "Take the risk", "Trust the process",
    "Wake up and be awesome", "Your only limit is you", "Action is the key", "Always be learning", "Aspire to inspire",
    "Be a voice, not an echo", "Be bold, be brave", "Be fearless", "Better late than never", "Challenge yourself",
    "Collect moments, not things", "Commit to your goals", "Confidence is key", "Create your own sunshine", "Creativity takes courage",
    "Determination leads to success", "Do more of what makes you happy", "Don't dream it, be it", "Don't quit your day dream", "Dream it. Wish it. Do it.",
    "Effort is everything", "Enjoy the little things", "Every day is a second chance", "Explore the unexplored", "Fail forward",
    "Find your fire", "Focus on your potential", "Get it done", "Go for it", "Go the extra mile",
    "Gratitude changes everything", "Grow through what you go through", "Hard work pays off", "Have faith in your dreams", "Hold the vision, trust the process",
    "Hustle and heart will set you apart", "I can and I will", "Imagine the possibilities", "Inhale courage, exhale fear", "Innovation is the way",
    "Inspire others", "It's a beautiful day", "Keep going, keep growing", "Kindness is free", "Let your light shine",
    "Life is a journey", "Listen to your soul", "Live a life you love", "Live, laugh, love", "Look for the magic in every day",
    "Love yourself first", "Make today count", "Mindset is everything", "Never look back", "No guts, no glory",
    "Nothing is impossible", "One day at a time", "Opportunity is everywhere", "Passion is power", "Patience is a virtue",
    "Persistence prevails", "Play hard, work harder", "Practice makes perfect", "Purpose drives us", "Quality over quantity",
    "Reach for the stars", "Remember why you started", "Respect the journey", "Rise and grind", "Seek adventure",
    "Self-love is the best love", "She turned her can'ts into cans", "Shoot for the moon", "Show up and shine", "Small steps, big results",
    "Stay curious", "Stay dedicated", "Stay focused", "Stay humble", "Stay inspired",
    "Stay wild", "Strive for greatness", "Take it easy", "The best is yet to come", "The future is bright",
    "The sky is the limit", "The time is now", "Think outside the box", "Today is a gift", "Together we can",
    "Turn your dreams into reality", "Unleash your potential", "Victory is sweet", "Vision is the art of seeing the invisible", "Wait for nothing",
    "Way of the warrior", "We are the champions", "Whatever it takes", "Win from within", "Work hard, play hard",
    "Yes you can", "You can do anything", "You got this", "You only live once", "Your life, your choice",
    "Abundance is a mindset", "Adventure awaits", "All is well", "Always keep fighting", "Amplify your impact",
    "Art is everywhere", "Be a light", "Be authentic", "Be grateful", "Be present",
    "Begin again", "Beyond limits", "Build your empire", "Call to action", "Celebrate every win",
    "Change is good", "Chase excellence", "Choose kindness", "Climb the mountain", "Dare to dream",
    "Design your life", "Diligence is the mother of good luck", "Discipline equals freedom", "Do it with passion", "Dream beyond borders",
    "Elevate your game", "Embrace the journey", "Empower yourself", "Endless possibilities", "Energy flows where intention goes",
    "Enjoy the ride", "Excel in all you do", "Expand your horizons", "Expect greatness", "Explore your world",
    "Fearless heart", "Feel the rhythm", "Find your balance", "Find your flow", "Find your peace",
    "Focus on what matters", "For the win", "Forgive and forget", "Fortune favors the bold", "Fuel your fire",
    "Full steam ahead", "Get after it", "Give it your all", "Go big or go home", "Go get 'em",
    "Gold in every moment", "Good vibes only", "Grace under pressure", "Great things are coming", "Grit and grace",
    "Happiness looks good on you", "Harmony in life", "Head held high", "Heart of a lion", "Heighten your senses",
    "Honesty is the best policy", "Hope is a waking dream", "Humble and hungry", "I am the captain of my soul", "Ignite your passion",
    "Impact over intention", "Inner strength", "Inspiring greatness", "Into the blue", "Invest in yourself",
    "It's all good", "Journey to the top", "Just breathe", "Keep the faith", "Lead by example",
    "Lead from the heart", "Learn and grow", "Legacy in the making", "Let it be", "Level up",
    "Life is what you make it", "Limitless potential", "Live bold", "Live with purpose", "Love unconditionally",
    "Make magic happen", "Make your mark", "Master your mind", "Mindfulness matters", "Mission possible",
    "Momentum is key", "Never settle", "No excuses", "Nothing can stop you", "One life, one chance",
    "Own your story", "Pave your own path", "Peace of mind", "Persistence is powerful", "Positive vibes only",
    "Power through", "Pure intentions", "Push your boundaries", "Quality of life", "Quiet confidence",
    "Radiate positivity", "Raise the bar", "Realize your dreams", "Refine your craft", "Relentless pursuit",
    "Resilience is beautiful", "Respect the hustle", "Rise above", "See the beauty", "Seek the truth",
    "Set the trend", "Simplify your life", "Sparkle every day", "Speak your truth", "Stay authentic",
    "Success is your duty", "Surrender is not an option", "Swift action brings results", "Take charge", "Take decisive steps",
    "Taste victory", "Teach others what you learn", "The journey is the destination", "The power of now", "The sky's the limit",
    "Think for yourself", "This is your moment", "Time waits for no one", "To achieve the impossible", "Today is your opportunity",
    "Triumph is inevitable", "Trust your instincts", "Turn obstacles into opportunities", "Unity creates strength",
    "Unleash your creativity", "Use your voice", "Victory belongs to those who act", "Wake up with purpose",
    "Walk your own path", "Warrior's heart", "Wealth begins in the mind", "Welcome challenges", "Work while others sleep",
    "Worship only the Truth", "Your only competition is yesterday", "Your potential is limitless",
    "Create your own destiny",
    "Live with purpose",
    "Turn ideas into action",
    "Be relentless",
    "Embrace uncertainty",
    "Celebrate progress",
    "Think bigger",
    "Cultivate gratitude",
    "Stay hungry",
    "Make impact",
    "Keep evolving",
    "Lead with empathy",
    "Grow continuously",
    "Pursue excellence",
    "Trust the process",

    // --- 道德經 (Dao De Jing) ---
    "道可道，非常道",
    "名可名，非常名",
    "上善若水，水善利萬物而不爭",
    "人法地，地法天，天法道，道法自然",
    "千里之行，始於足下",
    "為無為，則無不治",
    "知人者智，自知者明",
    "勝人者有力，自勝者強",
    "大巧若拙，大辯若訥",
    "天地不仁，以萬物為芻狗",
    "見素抱樸，少私寡慾",
    "禍兮福之所倚，福兮禍之所伏",

    // --- 心經 (Heart Sutra) ---
    "色即是空，空即是色",
    "受想行識，亦復如是",
    "心無罣礙，無罣礙故，無有恐怖",
    "照見五蘊皆空，度一切苦厄",
    "不生不滅，不垢不淨，不增不減",
    "遠離顛倒夢想，究竟涅槃",
    "揭諦揭諦，波羅揭諦，波羅僧揭諦，菩提薩婆訶",

    // --- 易經 (I Ching) ---
    "天行健，君子以自強不息",
    "地勢坤，君子以厚德載物",
    "窮則變，變則通，通則久",
    "安而不忘危，存而不忘亡",
    "積善之家，必有餘慶",
    "易窮則變，變則通",
    "同聲相應，同氣相求",
    "君子藏器於身，待時而動",
    "日新之謂盛德，生生之謂易",

    // --- 金剛經 (Diamond Sutra) ---
    "一切有為法，如夢幻泡影",
    "如露亦如電，應作如是觀",
    "凡所有相，皆是虛妄",
    "若見諸相非相，即見如來",
    "應無所住，而生其心",
    "過去心不可得，現在心不可得，未來心不可得",
    "法尚應捨，何況非法",
    "不取於相，如如不動"
];
